# Generated by Django 4.1.2 on 2022-10-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants', models.IntegerField()),
                ('company_size', models.TextField()),
                ('company_type', models.TextField()),
                ('full_time_or_other', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('site_scraped_from', models.TextField()),
                ('entry_level', models.TextField()),
                ('language_of_description', models.CharField(max_length=2)),
            ],
        ),
    ]
