# Generated by Django 4.1.2 on 2022-10-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_jobs', '0003_alter_jobposting_language_of_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
