# Generated by Django 4.1.2 on 2022-10-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_jobs', '0004_alter_jobposting_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
