# Generated by Django 4.1.2 on 2022-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_jobs', '0005_jobposting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
